### ISSUE TITLE
katana-assistant-endpoint.py error

### ISSUE THREAD

**Issue by ktfth** [katanaml/katana-assistant#4]
The startup fail when i try to initiate the server

0|katana-assistant-endpoint  | Traceback (most recent call last):
0|katana-assistant-endpoint  |   File "/home/kaique/war/katana-assistant/mlmodels/katana-assistant-endpoint.py", line 98, in <module>
0|katana-assistant-endpoint  |     classify_local('Hello, good day!')
0|katana-assistant-endpoint  |   File "/home/kaique/war/katana-assistant/mlmodels/katana-assistant-endpoint.py", line 82, in classify_local
0|katana-assistant-endpoint  |     results = model.predict([input_data])[0]
0|katana-assistant-endpoint  |   File "/home/kaique/miniconda3/envs/av/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1582, in predict
0|katana-assistant-endpoint  |     with self.distribute_strategy.scope():
0|katana-assistant-endpoint  |   File "/home/kaique/miniconda3/envs/av/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 689, in distribute_strategy
0|katana-assistant-endpoint  |     return self._distribution_strategy or ds_context.get_strategy()
0|katana-assistant-endpoint  | AttributeError: 'Sequential' object has no attribute '_distribution_strategy'

**Comment by ktfth** [comment]
Solved saving/loading using the keras api.

**Comment by abaranovskis-redsamurai** [comment]
Closing as solved

**Comment by Starteya** [comment]
> The startup fail when i try to initiate the server
> 
> 0|katana-assistant-endpoint | Traceback (most recent call last):
> 0|katana-assistant-endpoint | File "/home/kaique/war/katana-assistant/mlmodels/katana-assistant-endpoint.py", line 98, in
> 0|katana-assistant-endpoint | classify_local('Hello, good day!')
> 0|katana-assistant-endpoint | File "/home/kaique/war/katana-assistant/mlmodels/katana-assistant-endpoint.py", line 82, in classify_local
> 0|katana-assistant-endpoint | results = model.predict([input_data])[0]
> 0|katana-assistant-endpoint | File "/home/kaique/miniconda3/envs/av/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1582, in predict
> 0|katana-assistant-endpoint | with self.distribute_strategy.scope():
> 0|katana-assistant-endpoint | File "/home/kaique/miniconda3/envs/av/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 689, in distribute_strategy
> 0|katana-assistant-endpoint | return self._distribution_strategy or ds_context.get_strategy()
> 0|katana-assistant-endpoint | AttributeError: 'Sequential' object has no attribute '_distribution_strategy'

Having the same issue. Could you elaborate on how this was solved?

**Comment by abaranovskis-redsamurai** [comment]
In the imports section, try to change import for Keras, to be imported from TensorFlow package.
